# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Mohamad El-Husseini"
email: "husseini.mel@gmail.com"
description: "The personal website and portfolio of Mohamad El-Husseini."

# The subpath of your site, e.g. /blog
url: "http://mohamad.im" # the base hostname & protocol for your site
baseurl: ""
blog_url: "http://blog.mohamad.im"

# Use these to easily build social navs
social_links:
  - name: "email"
    url: "husseini.mel@gmail.com"
    type: "email"
  - name: "stackoverflow"
    url: "https://stackoverflow.com/users/276959/mohamad?tab=profile"
  - name: "github"
    url: "https://github.com/abitdodgy"
  - name: "instagram"
    url: "https://instagram.com/abitdodgy"
  - name: "twitter"
    url: "https://twitter.com/abitdodgy"

# Build settings
markdown: kramdown

gems: []

collections:
  - projects
  - instagrams

# This constructs the languages bar
languages:
  - title: "Ruby"
    ratio: "30"
  - title: "Elixir"
    ratio: "10"
  - title: "SCSS"
    ratio: "20"
  - title: "CoffeeScript"
    ratio: "10"
  - title: "JavaScript"
    ratio: "10"
  - title: "CSS"
    ratio: "20"


